TP 2 Restaurant/TP 2 Restaurant/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IRDB.Models
{
    public class Restaurant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public int Cuisine_Id { get; set; }
        public int PriceRange_Id { get; set; }
        public bool BYOW { get; set; }
        public double Rating { get; set; }
        public string Logo_Id { get; set; }
        public virtual List<Rating> Ratings { get; set; }
        [ForeignKey("Cuisine_Id")]
        public virtual Cuisine Cuisine { get; set; }
        [ForeignKey("PriceRange_Id")]
        public virtual PriceRange PriceRange { get; set; }


        public RestaurantView ToRestaurantView()
        {
            RestaurantView restaurantView = new RestaurantView();
            restaurantView.Id = Id;
            restaurantView.Name = Name;
            restaurantView.Address = Address;
            restaurantView.ZipCode = ZipCode.ToUpper();
            restaurantView.Phone = Phone;
            restaurantView.Website = Website;
            restaurantView.Cuisine_Id = Cuisine_Id;
            restaurantView.PriceRange_Id = PriceRange_Id;
            restaurantView.BYOW = BYOW;
            restaurantView.Rating = Rating;
            restaurantView.Logo_Id = Logo_Id;
            if (Cuisine != null)
                restaurantView.Cuisine = Cuisine.Name;
            if (PriceRange != null)
                restaurantView.PriceRange = PriceRange.Name;
            if (Ratings != null)
            {
                restaurantView.NbRatings = Ratings.Count;
            }
            return restaurantView;
        }

        public void Update(Restaurant restaurant)
        {
            Name = restaurant.Name;
            Address = restaurant.Address;
            ZipCode = restaurant.ZipCode;
            Phone = restaurant.Phone;
            Website = restaurant.Website;
            Cuisine_Id = restaurant.Cuisine_Id;
            PriceRange_Id = restaurant.PriceRange_Id;
            BYOW = restaurant.BYOW;
            Rating = restaurant.Rating;
            Logo_Id = restaurant.Logo_Id;
        }
    }

    public class RestaurantView
    {
        public int Id { get; set; }

        [Display(Name = "Nom")]
        [StringLength(50), Required(ErrorMessage = "Nom obligatoire.")]
        [RegularExpression(@"^((?!^Name$)[-a-zA-Z0-9àâäçèêëéìîïòôöùûüÿñÀÂÄÇÈÊËÉÌÎÏÒÔÖÙÛÜ_. '])+$", ErrorMessage = "Caractères illégaux.")]
        public string Name { get; set; }

        [Display(Name = "Adresse")]
        [StringLength(150), Required(ErrorMessage = "Adresse obligatoire.")]
        public string Address { get; set; }

        [Display(Name = "Code postal")]
        [StringLength(8), Required(ErrorMessage = "Code postal obligatoire.")]
        public string ZipCode { get; set; }

        [Display(Name = "Téléphone")]
        [StringLength(14), Required(ErrorMessage = "Téléphone obligatoire.")]
        public string Phone { get; set; }

        [Display(Name = "Site Web")]
        [StringLength(255), Required(ErrorMessage = "Site Web obligatoire.")]
        [Url(ErrorMessage = "Entrez un URL valide.")]
        public string Website { get; set; }

        [Display(Name = "Cuisine")]
        [Range(1, int.MaxValue, ErrorMessage = "Veuillez faire une sélection.")]
        public int Cuisine_Id { get; set; }

        [Display(Name = "Budget")]
        [Range(1, 5, ErrorMessage = "Veuillez faire une sélection.")]
        public int PriceRange_Id { get; set; }

        [Display(Name = "Apporter son vin")]
        public bool BYOW { get; set; }

        [Display(Name = "Evaluations")]
        public double Rating { get; set; }

        [Display(Name = "Logo")]
        public string Logo_Id { get; set; }

        private App_Utilities.ImageGUIDReference LogoReference;
        public RestaurantView()
        {
            Name = "";
            Address = "";
            ZipCode = "";
            Phone = "";
            Website = "";
            Cuisine_Id = 0;
            PriceRange_Id = 0;
            Logo_Id = "";
            Rating = 0;
            LogoReference = new App_Utilities.ImageGUIDReference(@"/RestaurantLogos/", @"restaurant-icon.png");
        }

        public string Cuisine { get; set; }
        public string PriceRange { get; set; }

        public int NbRatings { get; set; }

        public List<PriceRange> PriceRanges
        {
            get
            {
                using (var DB = new RestaurantsEntities())
                {
                    return DB.PriceRanges.ToList();
                }
            }
        }

        public List<Cuisine> Cuisines
        {
            get
            {
                using (var DB = new RestaurantsEntities())
                {
                    return DB.Cuisines.ToList();
                }
            }
        }

        public Restaurant ToRestaurant()
        {
            Restaurant restaurant = new Restaurant();
            restaurant.Id = Id;
            restaurant.Name = Name;
            restaurant.Address = Address;
            restaurant.ZipCode = ZipCode.ToUpper();
            restaurant.Phone = Phone;
            restaurant.Website = Website;
            restaurant.Cuisine_Id = Cuisine_Id;
            restaurant.PriceRange_Id = PriceRange_Id;
            restaurant.BYOW = BYOW;
            restaurant.Rating = Rating;
            restaurant.Logo_Id = Logo_Id;
            return restaurant;
        }
        public String GetLogoURL()
        {
            return LogoReference.GetURL(Logo_Id);
        }
        public void UpLoadLogo(HttpRequestBase Request)
        {
            Logo_Id = LogoReference.UpLoadImage(Request, Logo_Id);
        }
        public void RemoveLogo()
        {
            LogoReference.Remove(Logo_Id);
        }
    }
}

TP 2 Restaurant/TP 2 Restaurant/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IRDB.Models;

namespace TP_2_Restaurant.Controllers
{
    public class RestaurantsController : Controller
    {

        #region Tri des Restaurants et des Évaluations
        /// <summary>
        /// Initialise le tri à Par Nom
        /// et en ordre croissant
        /// </summary>
        private void InitializeSessionSort()
        {
            if (Session["RestaurantSortBy"] ==  null)
            {
                Session["RestaurantSortBy"] = "Name";
                Session["RestaurantSortAscendant"] = true;
            }
        }

        /// <summary>
        /// Tri selon l'attribut
        /// </summary>
        public ActionResult Sort(string by)
        {
            if (by == (string)Session["RestaurantSortBy"])
                // Inverse le tri
                Session["RestaurantSortAscendant"] = !(bool)Session["RestaurantSortAscendant"];
            else
                Session["RestaurantSortAscendant"] = true;
            //Donne le tri demander
            Session["RestaurantSortBy"] = by;
            //Redirige vers l'action Index()
            return RedirectToAction("Index");

        }
        /// <summary>
        /// Initialise le tri par Date
        /// et en ordre décroissant
        /// </summary>
        private void InitializeRatingSessionSort()
        {
            if (Session["RatingSortBy"] == null)
            {
                //Par défault,
                // Tri par date
                Session["RatingSortBy"] = "Date";
                // Du plus Récent
                Session["RatingSortAscendant"] = false;
            }
        }
        /// <summary>
        /// Tri des Évaluations
        /// </summary>
        /// <param name="by"></param>
        /// <returns>retourne à l'action Details du Id du restaurant</returns>
        public ActionResult SortRating(string by)
        {
            if (by == (string)Session["RatingSortBy"])
                Session["RatingSortAscendant"] = !(bool)Session["RatingSortAscendant"];
            else
                Session["RatingSortAscendant"] = true;

            Session["RatingSortBy"] = by;
            //prend le Id du restaurant consulté de la session courante
            Restaurant r = (Restaurant)Session["CurrentRestaurant"];
            return RedirectToAction("Details/" + r.Id);
        }
#endregion

        public ActionResult Index()
        {
            //Début en initialisant le tri de la liste des Restaurants
            InitializeSessionSort();
            using (var DB = new RestaurantsEntities())
            {
                return View(DB.SortedRestaurantList((string)Session["RestaurantSortBy"], (bool)Session["RestaurantSortAscendant"])); 
            }
        }
        /// <summary>
        /// Détails d'un restaurant
        /// qui affiche aussi une liste de toutes
        /// les évaluations de ce restaurant
        /// </summary>
        /// <param name="Id">le Id du Restaurant</param>
        /// <returns></returns>
        public ActionResult Details(int Id)
        {
            Restaurant resto = null; 
            using (var DB = new RestaurantsEntities())
            {
                resto = DB.Restaurants.Find(Id);
                if (resto != null)
                {
                    InitializeRatingSessionSort();
                    Session["CurrentRestaurant"] = resto;
                    ViewBag.RestaurantViews = resto.ToRestaurantView();
                    //ViewBag.Ratings = DB.Ratings.Where(r => r.Restaurant_Id == resto.Id);
                    return View(DB.SortedRatingList(Id,(string)Session["RatingSortBy"],(bool)Session["RatingSortAscendant"]));
                }
            }
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Création d'un retaurant
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            using (var DB = new RestaurantsEntities())
            {
                RestaurantView restoView = new RestaurantView();
                ViewBag.Cuisines = DB.Cuisines.ToList();
                ViewBag.PriceRanges = DB.PriceRanges.ToList();
                return View(restoView);
            }
        }
        /// <summary>
        /// Post de la Création d'un Restaurant
        /// </summary>
        /// <param name="restaurantView"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(RestaurantView restaurantView)
        {
            restaurantView.UpLoadLogo(Request);
            using (var DB = new RestaurantsEntities())
            {
                ViewBag.Cuisines = DB.Cuisines.ToList();
                ViewBag.PriceRanges = DB.PriceRanges.ToList();
                if (ModelState.IsValid)
                {
                    Restaurant resto = new Restaurant();
                    resto = restaurantView.ToRestaurant();

                    DB.Restaurants.Add(resto);
                    DB.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(restaurantView);
            }
        }
        /// <summary>
        /// Suppression d'un restaurants
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            using (var DB = new RestaurantsEntities())
            {
                Restaurant resto = DB.Restaurants.Find(id);
                if (resto != null)
                {
                    resto.ToRestaurantView().RemoveLogo();
                    DB.DeleteRestaurant(id);
                }
            }
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Modification du restaurant
        /// </summary>
        /// <param name="id">Le Id du Restaurant à modifier</param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            Restaurant resto = null;
            using (var DB = new RestaurantsEntities())
            {
                resto = DB.Restaurants.Find(id);
                if (resto != null)
                {
                    RestaurantView restoView = new RestaurantView();
                    ViewBag.Cuisines = DB.Cuisines.ToList();
                    ViewBag.PriceRanges = DB.PriceRanges.ToList();
                    restoView = resto.ToRestaurantView();
                    return View(restoView);
                }
            }
            return RedirectToAction("Index");

        }
        /// <summary>
        /// Post de la Modification du restaurant
        /// </summary>
        /// <param name="restaurantView"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(RestaurantView restaurantView)
        {
            restaurantView.UpLoadLogo(Request);
            using (var db = new RestaurantsEntities()) { db.Update(restaurantView.ToRestaurant()); }
            return RedirectToAction("Index");
        }
    }
}

TP 2 Restaurant/TP 2 Restaurant/Views/Restaurants/Create.cshtml
@model IRDB.Models.RestaurantView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Restaurants", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>RestaurantView</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <!--Nom-->
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Adresse Postal-->
        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Code Postal-->
        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control zipcode" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Numéro de Téléphone-->
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control phone" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Site Web-->
        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Type de Cuisine-->
        <div class="form-group">
            @Html.LabelFor(model => model.Cuisine_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <!--Sélectionné par un ComboBox-->
                @Helper.ComboBox(ViewBag.Cuisines, "Cuisine_Id")
                @Html.ValidationMessageFor(model => model.Cuisine_Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Type de Budget-->
        <div class="form-group">
            @Html.LabelFor(model => model.PriceRange_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <!--Sélectionné par un ComboBox-->
                @Helper.ComboBox(ViewBag.PriceRanges, "PriceRange_Id")
                @Html.ValidationMessageFor(model => model.PriceRange_Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Apporter son Vin (bool)-->
        <div class="form-group">
            @Html.LabelFor(model => model.BYOW, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.BYOW)
                    @Html.ValidationMessageFor(model => model.BYOW, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <!--Selection du Logo du Restaurant-->
        <div class="form-group">
            @Html.LabelFor(model => model.Logo_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Helper.ImageUpLoader(Url, Model.GetLogoURL(), "Cliquez pour choisir la photo...", "max-width:280px;")
            </div>
        </div>
        <!--Button de soumission du restaurant-->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<!--Boutton de retour-->
<div>
    @Helper.IconAction(Url, "Index", "Back", "Retour a la liste des restaurants")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TP 2 Restaurant/TP 2 Restaurant/Views/Restaurants/Details.cshtml
@*Ced 12 avril*@

<!--Reçois la list trier des rating de ce Restaurant-->
@model IEnumerable<IRDB.Models.RatingView>


@{
    ViewBag.Title = "Details";
 }

<!--En-tete Detail du restaurant-->
<!---->
<br />
<table style="font-size:larger">
    <tr>
        <td rowspan="6" style="padding-right:6px;">
            <a href="@ViewBag.RestaurantViews.Website" target="_blank" data-toggle="tooltip" title="@ViewBag.RestaurantViews.Website">
                <img src="@Url.Content(ViewBag.RestaurantViews.GetLogoURL())" class="MediumPhoto" />
            </a>
        </td>
        <td>
            <table>
                <tr>
                    <td>
                        <!--Name-->
                        <span style="font-size:x-large; font-weight:700">@ViewBag.RestaurantViews.Name</span>
                    </td>
                    <td>
                        <!--Rating-->
                        @Helper.RatingBar("Evaluation", ViewBag.RestaurantViews.Rating, true)
                    </td>
                    <td>
                        <!--NbRating-->
                        <span style="font-size:large;">(@ViewBag.RestaurantViews.NbRatings)</span>
                    </td>
                </tr>
            </table>
        </td>
        <td rowspan="6">
            <!--Image BYOW-->
            @if (ViewBag.RestaurantViews.BYOW)
            {
                <img src="~/Content/UI_Images/Image_BYOW.png" class="MediumPhoto" />
            }
        </td>
    </tr>
    <tr>
        <td>
            <!--Adress-->
            <a href="https://www.google.ca/maps/place/ @ViewBag.RestaurantViews.Address" target="_blank">
                @ViewBag.RestaurantViews.Address
            </a>
        </td>
    </tr>
    <tr>
        <td>
            <!--Phone-->
            @ViewBag.RestaurantViews.Phone
        </td>
    </tr>
    <tr>
        <td>
            <table>
                <tr>
                    <td>Cuisine:</td>
                    <!--Cuisine-->
                    <td>@ViewBag.RestaurantViews.Cuisine</td>
                    <td>&nbsp;&nbsp;</td>
                    <!--PriceRating-->
                    <td><b style="color:goldenrod">
                            @Html.DisplayFor(modelItem => ((IRDB.Models.Restaurant)Session["CurrentRestaurant"]).PriceRange.Name)
                        </b>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <!--<tr>
        <td></td>
    </tr>-->
</table>



<br />
<br />



<!--Lister tout les Ratings (Évaluations)-->
<table class="table">
    <tbody>
        <tr>
            <th class="col-md-2 sorted_header">
                @Helper.SortAction(Url, "SortRating", Html.DisplayNameFor(model => model.Rating_Date).ToString(), "Ratings", "Date")
            </th>
            <th class="col-md-2 sorted_header">
                @Helper.SortAction(Url, "SortRating", Html.DisplayNameFor(model => model.Rating_Value).ToString(), "Ratings", "Rating")
            </th>
            <th class="col-md-2 sorted_header">
                @Helper.SortAction(Url, "SortRating", Html.DisplayNameFor(model => model.Rater_Name).ToString(), "Ratings", "Name")

            </th>
            <th class="col-md-5">
                Commentaires
            </th>
            <th style="min-width:40px">
                @Helper.IconAction(Url, "../Ratings/Create", "Add", "Ajouter une Évaluation!")
            </th>
            <th style="min-width:40px"></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr class="data_row" style="">
                <td style="min-width:90px;height:25px;">
                    <!--rating Date-->
                    @item.Rating_Date.ToString()
                </td>
                <td>
                    <!--Rating value-->
                    @Helper.RatingBar("Evaluation", item.Rating_Value, true)
                </td>
                <td>
                    <!--Rater Name-->
                    @item.Rater_Name
                </td>
                <td>
                    <!--Comment-->
                    @item.Comments
                </td>
                <!--Action Button-->
                <td style="width:80px">
                    <!--Button Edit-->
                    @Helper.IconAction(Url, "../Ratings/Edit/" + item.Id.ToString(), "Edit", "Modifier l'évaluation de " + item.Rater_Name)
                </td>
                <td>
                    <!--Button Delete-->
                    @Helper.IconConfirmedAction(Url, "../Ratings/Delete/" + item.Id.ToString(), "Delete", "Effacer l'évaluation de " + item.Rater_Name)
                </td>
            </tr>
        }
    </tbody>
</table>
<!--Boutton de retour-->
<div>
    @Helper.IconAction(Url, "Index", "Back", "Retour au Restaurant")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TP 2 Restaurant/TP 2 Restaurant/Views/Restaurants/Edit.cshtml
@model IRDB.Models.RestaurantView

@{
    ViewBag.Title = "Edit";
}

<h2>Modification</h2>


@using (Html.BeginForm("Edit", "Restaurants", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Rating)
    @Html.HiddenFor(model => model.NbRatings)
    @Html.HiddenFor(model => model.Logo_Id)

        <!--Nom du Restaurant-->
        <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Adresse Postal-->
        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Code Postal-->
        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control zipcode" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Numéro de Téléphone-->
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control phone" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Site Web-->
        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Type de Cuisine-->
        <div class="form-group">
            @Html.LabelFor(model => model.Cuisine_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <!--Selectionné par un ComboxBox-->
                @Helper.ComboBox(ViewBag.Cuisines, "Cuisine_Id", Model.Cuisine_Id)
                @Html.ValidationMessageFor(model => model.Cuisine_Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Type de Budget-->
        <div class="form-group">
            @Html.LabelFor(model => model.PriceRange_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <!--Selectionné par un ComboxBox-->
                @Helper.ComboBox(ViewBag.PriceRanges, "PriceRange_Id", Model.PriceRange_Id)
                @Html.ValidationMessageFor(model => model.PriceRange_Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--Apporté son Vin (bool)-->
        <div class="form-group">
            @Html.LabelFor(model => model.BYOW, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.BYOW)
                    @Html.ValidationMessageFor(model => model.BYOW, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <!--Selection de l'imgage-->
        <div class="form-group">
            @Html.LabelFor(model => model.Logo_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Helper.ImageUpLoader(Url, Model.GetLogoURL(), "Cliquez pour choisir la photo...", "max-width:280px;")
            </div>
        </div>
        <!--Button Enregistrer-->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<!--Button Retour-->
<div>
    @Helper.IconAction(Url, "Index", "Back", "Retour a la liste des restaurants")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}